version: '3.8'

services:
  frontend:
    image: frontend_image
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    image: backend_image
    build:
      context: ./backend
    ports:
      - "2000:2000"